# Линейная алгебра

Линейная алгебра - это раздел математики, изучающий линейные уравнения, векторы, матрицы и их свойства. Она имеет множество приложений в различных областях, включая машинное обучение и компьютерную графику.

Вот основные концепции линейной алгебры:

--------------

## Векторы

Вектор - это объект, имеющий направление и длину. Он может быть представлен в виде числовой последовательности или в графическом виде. Вектор может быть складываемым и умножаемым на число (скаляр).

--------------

## Матрицы

Матрица - это таблица чисел, расположенных в виде прямоугольной сетки. Она может использоваться для представления системы линейных уравнений и выполнения операций с векторами.

--------------

## Операции над векторами и матрицами

Операции над векторами включают сложение, вычитание, скалярное произведение и векторное произведение. Операции над матрицами включают сложение, вычитание и умножение.

--------------

## Системы линейных уравнений

Система линейных уравнений - это набор уравнений, каждое из которых имеет вид $a1x1 + a2x2 + ... + anxn = b$, где $a1, a2, ..., an$ - коэффициенты, $x1, x2, ..., xn$ - неизвестные и $b$ - константа. Решение системы линейных уравнений - это значения $x1, x2, ..., xn$, которые удовлетворяют всем уравнениям системы.

--------------

## Собственные значения и собственные векторы

Собственными значениями и собственными векторами матрицы называются соответственно числа и векторы, которые остаются параллельными своему направлению при линейном преобразовании этой матрицы.

Для лучшего понимания этого понятия рассмотрим матричное умножение. Пусть дана квадратная матрица $A$ порядка n и вектор x. Тогда произведение $Ax$ будет новым вектором, который может иметь другую длину, направление и ориентацию, но лежать в той же плоскости, что и вектор x.

Собственный вектор v матрицы $A$ - это такой ненулевой вектор, для которого Ax равен просто скалярному произведению этого вектора на какое-то число λ, которое называется собственным значением:

$Av = λv$ 

Здесь λ - скаляр, называемый собственным значением матрицы $A$, а $v$ - ненулевой вектор, называемый собственным вектором, который соответствует λ.

Другими словами, при умножении матрицы $A$ на собственный вектор $v$ мы получаем новый вектор, который параллелен вектору $v$ и имеет длину, равную произведению λ на длину вектора $v$.

### Алгоритм

Собственные значения и собственные векторы матрицы являются важными в линейной алгебре, так как они позволяют нам понять, как матрица воздействует на пространство, в котором она действует, и как изменяются векторы при этом воздействии. Они также широко используются во многих областях математики и естественных наук, включая физику, экономику, инженерию и многие другие.

Рассмотрим матрицу $A = \begin{pmatrix} 3 & -1 \\ 1 & 3 \end{pmatrix}$. Чтобы найти ее собственные значения и собственные векторы, решим соответствующие уравнения.

Сначала найдем собственные значения. Для этого нужно найти такие значения $\lambda$, при которых определитель матрицы $A - \lambda I$ равен нулю:

$\begin{pmatrix} 3 - \lambda & 1 \\ -1 & 3 - \lambda \end{pmatrix} = 0$.

Раскрывая определитель, получим квадратное уравнение:

$\lambda^2 - 6\lambda + 8 = 0$

Где: 

$\lambda_1 = 2$, $\lambda_2 = 4$

Теперь найдем собственные векторы для каждого из найденных собственных значений. Для этого нужно решить систему уравнений $(A - \lambda I)x = 0$.

Для $\lambda_1 = 2$:

$(A - 2I)x = \begin{pmatrix} 1 & -1 \\ 1 & 1 \end{pmatrix} \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \end{pmatrix}$

Собственный вектор $x = \begin{pmatrix} 1 \\ 1 \end{pmatrix}$

Таким образом, собственное значение $\lambda_1 = 2$ соответствует собственному вектору $x = \begin{pmatrix} 1 \\ 1 \end{pmatrix}$.

--------------

## Определитель

Определитель - это числовая характеристика квадратной матрицы. Он вычисляется для матрицы определенного порядка и является скалярной величиной. 
Определитель матрицы A обозначается det(A) или |A|.

Вычисление определителя является важной операцией в линейной алгебре и используется для решения систем линейных уравнений, нахождения обратной матрицы,
 определения линейной независимости векторов и других задач.


$\det(A) = \sum_{\sigma \in S_n} \text{sgn}(\sigma) \prod_{i=1}^{n} a_{i,\sigma_i}$


Формула для нахождени определитля второго порядка: 

$\det\begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix} = a_{11}a_{22}-a_{12}a_{21}$

Формула для нахождения определителя третьего порядка:

$\det\begin{pmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{pmatrix} = a_{11}a_{22}a_{33} + a_{12}a_{23}a_{31} + a_{13}a_{21}a_{32} - a_{13}a_{22}a_{31} - a_{11}a_{23}a_{32} - a_{12}a_{21}a_{33}$

----

Линейная алгебра - это широкий раздел математики, который имеет множество приложений в науке и технике. Она играет важную роль в различных областях, включая компьютерную графику, машинное обучение и науку о данных.

----



In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sc

In [18]:
# создание вектора из списка
v = np.array([1, 2, 3])

# создание матрицы из списка списков
m = np.array([[1, 2], [3, 4]])


In [3]:
# создание векторов
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# сложение векторов
v_sum = v1 + v2

# вычитание векторов
v_diff = v1 - v2

# создание матриц
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

# сложение матриц
m_sum = m1 + m2

# вычитание матриц
m_diff = m1 - m2


In [20]:
# создание вектора
v = np.array([1, 2, 3])

# умножение на скаляр
v_scaled = 2 * v

# создание матрицы
m = np.array([[1, 2], [3, 4]])

# умножение на скаляр
m_scaled = 2 * m


In [21]:
# создание векторов
v1 = np.array([1, 2])
v2 = np.array([4, 5])


# умножение векторов (скалярное произведение)
v_dot = np.dot(v2, v1)

# создание матриц
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

# умножение матриц
m_dot = np.matmul(m1, m2)

# умножение матрицы на вектор
mv_dot = np.dot(m1, v1)

In [22]:
# создание вектора-столбца
vector_col = np.array([[1], [2], [3]])

# транспонирование вектора-столбца в вектор-строку
vector_row = vector_col.transpose()

# или также можно использовать свойство T для транспонирования
vector_row = vector_col.T


In [23]:
# создание матрицы размерности (3, 2)
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

# транспонирование матрицы
transposed_matrix = matrix.T


In [29]:
# Создание матрицы
A = np.array([[1, 2, 1],
              [3, 4, 3],
              [1, 1, 1]])

# Вычисление собственных значений и собственных векторов
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)


Собственные значения:
[ 6.16227766e+00 -1.62277660e-01 -1.94711044e-16]

Собственные векторы:
[[-0.39133557 -0.8247362  -0.70710678]
 [-0.88634026  0.21848175  0.        ]
 [-0.24750235  0.52160897  0.70710678]]


In [25]:
# plt.plot(A)
# plt.plot(eigenvalues)
# plt.plot(eigenvectors)
# plt.show()

In [26]:
# Создание матрицы
A = np.array([[1, 2, 1],
              [3, 4, 3],
              [1, 1, 1]])
# Нахождение определителя матрицы
print(np.linalg.det(A))

0.0


In [16]:
import plotly.graph_objects as go
import numpy as np

# Задаем параметры осей
x = np.linspace(-10, 10, 1000)
y = 1 / (np.sqrt(x))

# Создаем объект Figure
fig = go.Figure()

# Добавляем график на объект Figure с красной линией
fig.add_trace(go.Scatter(x=x, y=y, mode='lines', name='1 / (1 + e^(-x))', line=dict(color='white')))

# Устанавливаем параметры оформления графика
fig.update_layout(
    xaxis_title='x',
    yaxis_title='y',
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
    font=dict(color='white')
)

# Добавляем горизонтальную линию, отражающую значение предела
fig.add_shape(type='line',
              x0=-11,
              y0=0,
              x1=11,
              y1=0,
              line=dict(color='red'))

# Выводим график
fig.show()




C:\Users\Matvey\AppData\Local\Temp\ipykernel_19784\3599821351.py:6: RuntimeWarning:

invalid value encountered in sqrt

